---
kind: pipeline
type: docker
name: CD

steps:
- name: restore cache
  image: drillster/drone-volume-cache
  volumes:
    - name: cache
      path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: generate
  image: node:18-alpine
  commands:
    - yarn install
    - yarn generate
  depends_on:
    - "restore cache"

- name: rebuild cache
  image: drillster/drone-volume-cache
  volumes:
    - name: cache
      path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules
  depends_on:
    - generate

- name: deploy-stable
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    target:
      from_secret: ssh_target
    source: dist/*
    strip_components: 1
    username:
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port:
      from_secret: ssh_port
  depends_on:
    - generate
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: deploy-devel
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    target:
      from_secret: ssh_target_devel
    source: dist/*
    strip_components: 1
    username:
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port:
      from_secret: ssh_port
  depends_on:
    - generate
  when:
    branch:
    - devel
    event:
      exclude:
      - pull_request
