#+title: phundrak.com

#+html: <a href="https://www.gnu.org/software/emacs/"><img src="https://img.shields.io/badge/Emacs-29.1-blueviolet.svg?style=flat-square&logo=GNU%20Emacs&logoColor=white" /></a>
#+html: <a href="https://orgmode.org/"><img src="https://img.shields.io/badge/Written%20with-Org%20mode-success?logo=Org&logoColor=white&style=flat-square"/></a>
#+html: <a href="https://v2.vuepress.vuejs.org/"><img src="https://img.shields.io/badge/Framework-Vuepress-42D392?logo=Vue.js&logoColor=white&style=flat-square"/></a>
#+html: <a href="https://phundrak.com"><img src="https://img.shields.io/badge/dynamic/json?label=Website&query=%24%5B%3A1%5D.status&url=https%3A%2F%2Fdrone.phundrak.com%2Fapi%2Frepos%2Fphundrak%2Fphundrak.com%2Fbuilds&style=flat-square&logo=buffer" /></a>

* Introduction
This is the repository for my website [[https://phundrak.com][phundrak.com]] which contains the
code available on the =main= branch. Code available on the =develop=
branch is available at [[https://beta.phundrak.com][beta.phundrak.com]].

* Structure of the project
This website is made with [[https://v2.vuepress.vuejs.org/][VuePress]], a Vue-powered static site
generator. You can find its Node.JS configuration in the [[file:package.json][package.json]]
file as well as its content and general configuration in the directory
[[file:content/][content]].

** Installing and running
In order to run the website, you firts need to export all the orgmode
files to Markdown files. I recommend using =ox-gfm= to do so. If you
don’t mind =package.el= installing it as well as =f.el=, you can run the
following command:
#+begin_src shell
emacs -Q --script export.el
#+end_src

To install the NPM dependencies for the project, run one of the
following commands:
#+begin_src shell
yarn
# or
npm install # delete the yarn.lock file before
#+end_src

To run the project, run one of the following commands using the same
package manager as above:
#+begin_src shell
yarn dev
# or
npm run dev
#+end_src

You can compile the website to a static website by running
#+begin_src shell
yarn build
# or
npm run build
#+end_src

The compiled version of the website can then be found in =content/.vuepress/dist=.
