#+setupfile: ../headers
#+language: lfn

* Crea de linguas
La /linguas construida/ (en engles /conlang/) es linguas artifis naseda de
la spirito de un persone, o a veses alga persones. Les es diferente de
linguas natural ce apare con la evolui de un lingua presedente parlada
par un popla completa dura multiple sentenios, como franses, engles,
putong, nion, o bahasa o cosa (/!Xhosa/).

Linguas construida pote ave diversa intende tra sua crea, pe:
- es parlada como otra linguas natural afin de es un lingua franca
  entre multiple comunias, como elefen o esperanto
- es un lingua secreta ce sola algun persones conose afin de comunica
  sin ce on comprende los
- esperia lo ce es posible linguisticamente, como [[https://en.wikipedia.org/wiki/Lojban][Lojban]] ce atenta a
  es la lingua la plu lojica
- completa un universo fantasial, como la linguas elfin de Tolkien o
  klingon de Star Trek
- sola es arte, como la pinta o la poesia.

En mea caso, la du ultima espicas es lo ce me impulsa a crea nova
linguas. Mea du projetas xef es [[https://conlang.phundrak.com/proto-nyqy][proto-ñyqy]] e [[https://conlang.phundrak.com/eittlandic][eittlansce]]. La prima es
un lingua prima ce se fundi sur no otra lingua, ma ce me va usa a crea
un familia linguistica completa, en ce eittlansce es desende de la
lingua de la vicinges, vea nordica, e ce se parla en la pais fantasial
de Eittland.

On pote trove plu de informa sur [[https://conlang.phundrak.com/][mea loca ueb de linguas construida]].

#+include: other-links
