#+title: Création de langues
#+setupfile: ./headers
#+language: fr

* Création de langues

Les /idéolangues/, ou /langues construites/ (en anglais /conlang/), sont des
langues construites et artificielles, nées de l’esprit d’une ou
parfois quelques personnes. Elles se distinguent ainsi des /langues
naturelles/ qui sont des langues ayant naturellement évolué depuis
d’autres langues plus anciennes, comme le Français, l’Anglais, le
Mandarin, le Japonais, le bahasa ou le !xhosa (oui, le point
d’exclamation fait partie de l’orthographe du nom de la langue).

Les idéolangues peuvent avoir différents buts lors de leur création,
par exemple :
- être parlées comme des langues naturelles par des individus afin de
  servir de /lingua franca/ entre plusieurs communautés linguistiques,
  comme le célèbre [[https://en.wikipedia.org/wiki/Esperanto][espéranto]] ou bien la [[https://elefen.org][lingua franca nova]]
- être une langue secrète que seules quelques personnes connaissent
  afin de communiquer entre eux sans que d’autres personnes puissent
  comprendre, un peu comme un argot, mais plus poussé encore
- être une expérience concrète de linguistique, comme le [[https://en.wikipedia.org/wiki/Lojban][lojban]] qui
  essaie d’être la langue la plus logique qui soit
- complémenter un univers littéraire, comme les langues elfiques de
  Tolkien ou le klingon de Star Trek
- juste être une forme d’art, comme la peinture ou la poésie

Dans mon cas, les deux dernières justifications sont celles qui me
poussent à créer de nouvelles langues. Mes deux projets principaux
actuellement sont le [[https://conlang.phundrak.com/proto-nyqy][proto-ñyqy]] et l’[[https://conlang.phundrak.com/eittlandic][éittlandais]]. La première est une
langue racine qui me permettra de développer toute une famille de
langues dans mon univers littéraire, tandis que la seconde s’inscrit
dans un exercice créatif de création d’un pays fictif présent dans
notre monde.

Plus d’informations peuvent être trouvées sur [[https://conlang.phundrak.com/][mon site
d’idéolinguistique]] (en anglais)
