#+setupfile: ./headers
#+language: fr

* Accueil

Bonjour, je suis Lucien Cartier-Tilet, un consultant chez [[Aubay][https://aubay.com/]].

J’ai étudié pour mon Master 2 THYP
(/Technologies de l’Hypermédia/) à l’Université Vincennes Saint-Denis
(Paris 8).

J’ai travaillé chez VoxWave de 2012 à 2018 en tant que co-fondateur et
directeur technique de l’entreprise. J’y ai notamment développé les
chanteuses virtuelles francophones nommées ALYS et LEORA.

Je suis un enthousiaste du logiciel libre, utilisant Linux depuis 2008
et Emacs depuis 2016.

Mes passe-temps principaux sont la programmation, aussi bien de la
programmation système que de la programmation web, et la construction
de langues et univers fictifs. J’aime aussi faire de l’escalade et
quand l’opportunité se présente, de la randonnée.

Ma langue maternelle est le Français, mais je parle également
couramment en anglais. J’ai également des bases en japonais, [[https://elefen.org][lingua
franca nova]], et en norvégien bokmål.

#+begin_export html
Ce site web est également disponible sur Gemini à l’adresse [gmi.phundrak.com](gemini://gmi.phundrak.com)!
#+end_export

#+include: other-links
