#+setupfile: ../headers
#+language: en

* Home
Hi, I’m Lucien Cartier-Tilet, a consultant working at [[Aubay][https://aubay.com/]].

I studied for my Masters 2 degree in THYP (in French: /Technologies de l’Hypermédia/, in English: /Hypermedia Technologies/) at the Université Vincennes Saint-Denis (Paris 8).

I worked at VoxWave from 2012 to 2018 as its co-founder and CTO.
During that time, I developed French singing vocal libraries for vocal
synthesizers, known as ALYS and LEORA.

I’m a free software enthusiast, using GNU/Linux since 2008 and Emacs
since 2016.

I spend my personnal programming projects as well as on my constructed
worlds and languages. I also like to go climbing, and hiking whenever
I have the opportunity to.

I speak natively French, and English at a native level. I also speak
some Japanese, [[https://elefen.org][Lingua Franca Nova]], and Norwegian Bokmål.

#+begin_export html
This website is also available on Gemini as [gmi.phundrak.com/en](gemini://gmi.phundrak.com/en)!
#+end_export

#+include: other-links
