#+setupfile: ../headers
#+language: en

* Privacy
** Where is the website hosted?
This website is hosted on my private physical server, located in the
town of Bron in France, near Lyon. All of my websites are also hosted
on this server, except for [[https://labs.phundrak.com][=labs.phundrak.com=]] and =mail.phundrak.com=
which are hosted on servers rented to Scaleway and OVH France
respectively. These servers are also located in France.

** Cookies
*** What are cookies?
Cookies are small files a website saves on your computer or mobile
phone when you visit a website. Although not all sites make use of
them, they are nevertheless extremely common in order to allow
websites to function properly or function properly or more
efficiently.

This website uses some functional cookies in order to remember your
preferences, such as your preferred language or its colour theme.
These cookies are not and cannot be used to track you.

However, as this site is protected by Cloudflare, they may also host
some cookies to remember, for example, that your browser is safe or to
record traffic to the site.

*** How can I control cookies on my computer?
If you don't want Cloudflare to record your browsing activity on my
website, a good ad blocker should do the trick. I personally recommend
[[https://ublockorigin.com/][uBlock Origin]], one of the most effective ad blockers I know of if not
the most effective one.

You can also manually delete cookies from your browser, but given the
number of browsers out there, it might be quicker for you to look up
DuckDuckGo, Qwant or Startpage to do this for your current browser (if
you're worried about cookie usage, I guess you'll want to avoid
Google).

*** What about other methods of tracking users?
There are other more subtle methods of tracking someone on the
internet, or even via emails or any web content rendered on the
screen, such as web beacons (minuscule, invisible images). It is also
possible to store Flash cookies or local shared objects.

*** But is there any tracking at all on this website?
Well, there is, but it absolutely respects your privacy. I use my own
instance of [[https://umami.is][Umami]] which is an analytics service that is fully GDPR and
CCPA compliant. In short, when you visit a web page, some data get
sent to my service, but nothing that can identify you. If you come
back an hour later, I won’t have any indication that you are the same
person.

If you still worry about your privacy, you have two options:
- Activate the Do Not Track setting of your browser (which Umami will
  honour)
- Block the domain =umami.phundrak.com= in uBlock Origin (the only
  ad blocker I will ever trust)

** Is there targeted advertisement on this website?
There’s no advertisement to begin with, and never will be. If you see
any, check your computer and browser for virus, that is not normal. If
it indeed comes from my website, it means it has been hacked. If you
can see in this website’s repository that I myself added ads, it means
that I either lost my morals, or that I have been kidnapped and this
is a cry for help.

** How often is this page updated?
It is updated from time to time to reflect any changes in how my
website behaves, or if I notice errors on this page (such as typos).

** I have other questions
And I have the answers! I’ll be more than happy to chat with you by
email, feel free to send me one at [[mailto:lucien@phundrak.com][lucien@phundrak.com]].

#+include: other-links
