#+setupfile: ../headers
#+language: en

#+begin_export html
---
title: Vocal Synthesis
---
#+end_export

* My works in vocal synthesis
From 2011 to 2018, I worked as an amateur and professional in singing
vocal synthesis. More precisely, I was creating vocal libraries used
by various libraries, mainly UTAU and Alter/Ego.

** UTAU
I began working with UTAU first by the end of 2011 on an unnamed and
deleted Japanese vocal library. While I didn’t maintain it for long,
mainly due to its bad recording quality (I recorded it with a low-end
desktop microphone) and configuration, it did teach me the basics of
creating vocal libraries and working with audio files.

In October 14th, 2012, I released my second vocal library, named
/BSUP01 KEINE Tashi JPN VCV/ which was of higher quality both due to the
recording equipment, manner of recording, and configuration, though
still relatively average for the time. My best work with this series
of vocal libraries was /BSUP01 KEINE Tashi JPN Extend Power/, a
high-energy voice made in similar circumstances but with yet again
better know-how.

This series of vocal libraries also featured /BSUP01 KEINE Tashi TIB
CVVC/ and /BSUP02 Drolma TIB/, the two first Tibetan vocal libraries for
singing vocal synthesis worldwide.

I later created in UTAU /ALYS 001 JPN/, /ALYS 001 FRA/, and /ALYS 002 FRA/
as prototypes, known as /ALYS4UTAU/, for our upcoming product while
working at VoxWave.

While all these vocal libraries have been discontinued, vocal
libraries for /BSUP01 KEINE Tashi/ and /ALYS/ are available for download.
Please refer to the following pages:
- BSUP01 KEINE Tashi :: [[file:./keine-tashi.org][BSUP01 KEINE Tashi]]
- ALYS :: [[https://labs.phundrak.com/ALYS/ALYS][ALYS for Alter/Ego download]]

** Alter/Ego
[[https://www.plogue.com/products/alter-ego.html][Alter/Ego]] is a singing vocal synthesis engine made by [[https://www.plogue.com/][Plogue Inc.]].
ALYS was its first commercial vocal library as well as the first
professional singing vocal library available in French.

Due to the architecture and behaviour of Alter/Ego, important changes
had to be done to the recording script for ALYS (later re-used for
LEORA). Including the development of the new recording scripts, the
initial development period for ALYS spanned well over a year, with
some additional eight to nine months for its first major update.

ALYS for Alter/Ego, also known as /ALYS4AE/, is available free of charge
as a module for Alter/Ego

#+include: other-links
